### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#181]
So far, I've only tested PyLink on Linux. Doing some testing on Windows (and possibly alternate platforms) should be looked into.

----
Problem 1: expiringdict from pip has no Python 3 support. This causes compilation to fail:

```
C:\Users\GLolol>pip install expiringdict ircmatch
Downloading/unpacking expiringdict
  Downloading expiringdict-1.1.3.tar.gz
  Running setup.py (path:C:\Users\GLolol\AppData\Local\Temp\pip_build_GLolol\expiringdict\setup.py) egg_info for package expiringdict
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Users\GLolol\AppData\Local\Temp\pip_build_GLolol\expiringdict\setup.py", line 2, in <module>
        import md5  # fix for "No module named _md5" error
    ImportError: No module named 'md5'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "C:\Users\GLolol\AppData\Local\Temp\pip_build_GLolol\expiringdict\setup.py", line 2, in <module>

    import md5  # fix for "No module named _md5" error

ImportError: No module named 'md5'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in C:\Users\GLolol\AppData\Local\Temp\pip_build_GLolol\expiringdict
Storing debug log for failure in C:\Users\GLolol\pip\pip.log
```

For relay, 9fe3373906a2e79fd860b9ffcbcfcccbafb40fa8 strips out the parts requiring expiringdict and puts kill protection, etc. in a new `servprotect` plugin.

**Comment by GLolol** [comment]
Problem 1: expiringdict from pip has no Python 3 support. This causes compilation to fail:

```
C:\Users\GLolol>pip install expiringdict ircmatch
Downloading/unpacking expiringdict
  Downloading expiringdict-1.1.3.tar.gz
  Running setup.py (path:C:\Users\GLolol\AppData\Local\Temp\pip_build_GLolol\expiringdict\setup.py) egg_info for package expiringdict
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Users\GLolol\AppData\Local\Temp\pip_build_GLolol\expiringdict\setup.py", line 2, in <module>
        import md5  # fix for "No module named _md5" error
    ImportError: No module named 'md5'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "C:\Users\GLolol\AppData\Local\Temp\pip_build_GLolol\expiringdict\setup.py", line 2, in <module>

    import md5  # fix for "No module named _md5" error

ImportError: No module named 'md5'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in C:\Users\GLolol\AppData\Local\Temp\pip_build_GLolol\expiringdict
Storing debug log for failure in C:\Users\GLolol\pip\pip.log
```

**Comment by GLolol** [comment]
Worksforme[tm]
