### ISSUE TITLE
relay: cascade of errors when networks disconnect too often

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#183]
edit: see https://github.com/GLolol/PyLink/issues/183#issuecomment-203709462 for further details.

```
00:17 <%PyLink> [WARNING] (apl) Disconnected from IRC: timeout: The read operation timed out
00:17 <%PyLink> [WARNING] (fun) Connection timed out.
00:17 <%PyLink> [ERROR] (fun) Failed to spawn server for 'ovd':
00:17 <%PyLink> Traceback (most recent call last):
00:17 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 260, in getRemoteUser
00:17 <%PyLink>     u = relayusers[(irc.name, user)][remoteirc.name]
00:17 <%PyLink> KeyError: 'fun'
00:17 <%PyLink> During handling of the above exception, another exception occurred:
00:17 <%PyLink> Traceback (most recent call last):
00:17 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 228, in getRemoteSid
00:17 <%PyLink>     sid = relayservers[irc.name][remoteirc.name]
00:17 <%PyLink> KeyError: 'ovd'
00:17 <%PyLink> During handling of the above exception, another exception occurred:
00:17 <%PyLink> Traceback (most recent call last):
00:17 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 236, in getRemoteSid
00:17 <%PyLink>     or remoteirc.name), endburst_delay=3)
00:17 <%PyLink>   File "/home/gl/pylink/protocols/inspircd.py", line 314, in spawnServer
00:17 <%PyLink>     raise ValueError('A server named %r already exists!' % name)
00:17 <%PyLink> ValueError: A server named 'ovd.relay' already exists!
00:17 <%PyLink> [ERROR] (fun) Failed to spawn server for 'ovd':
00:17 <%PyLink> Traceback (most recent call last):
00:17 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 228, in getRemoteSid
00:17 <%PyLink>     sid = relayservers[irc.name][remoteirc.name]
00:17 <%PyLink> KeyError: 'ovd'
00:17 <%PyLink> During handling of the above exception, another exception occurred:
00:17 <%PyLink> Traceback (most recent call last):
00:17 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 236, in getRemoteSid
00:17 <%PyLink>     or remoteirc.name), endburst_delay=3)
00:17 <%PyLink>   File "/home/gl/pylink/protocols/inspircd.py", line 314, in spawnServer
00:17 <%PyLink>     raise ValueError('A server named %r already exists!' % name)
00:17 <%PyLink> ValueError: A server named 'ovd.relay' already exists!
00:17 <%PyLink> [ERROR] (fun) _disconnect: Failed to close/shutdown socket.
00:17 <%PyLink> Traceback (most recent call last):
00:17 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 228, in getRemoteSid
00:17 <%PyLink>     sid = relayservers[irc.name][remoteirc.name]
00:17 <%PyLink> KeyError: 'ovd'
00:17 <%PyLink> During handling of the above exception, another exception occurred:
00:17 <%PyLink> Traceback (most recent call last):
00:17 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 236, in getRemoteSid
00:17 <%PyLink>     or remoteirc.name), endburst_delay=3)
00:17 <%PyLink>   File "/home/gl/pylink/protocols/inspircd.py", line 314, in spawnServer
00:17 <%PyLink>     raise ValueError('A server named %r already exists!' % name)
00:17 <%PyLink> ValueError: A server named 'ovd.relay' already exists!
00:17 <%PyLink> During handling of the above exception, another exception occurred:
00:17 <%PyLink> Traceback (most recent call last):
00:17 <%PyLink>   File "/home/gl/pylink/classes.py", line 306, in disconnect
00:17 <%PyLink>     self.socket.shutdown(socket.SHUT_RDWR)
00:17 <%PyLink>   File "/usr/lib/python3.4/ssl.py", line 783, in shutdown
00:17 <%PyLink>     socket.shutdown(self, how)
00:17 <%PyLink> OSError: [Errno 9] Bad file descriptor
00:17 <%PyLink> [ERROR] (apl) Unhandled exception caught in hook <function handle_endburst at 0x7fc47997d378> from plugin "relay"
00:17 <%PyLink> Traceback (most recent call last):
00:17 <%PyLink>   File "/home/gl/pylink/classes.py", line 396, in callHooks
00:17 <%PyLink>     hook_func(self, numeric, command, parsed_args)
00:17 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 1174, in handle_endburst
00:17 <%PyLink>     initializeAll(irc)
00:17 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 44, in initializeAll
00:17 <%PyLink>     initializeChannel(irc, channel)
00:17 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 413, in initializeChannel
00:17 <%PyLink>     relayJoins(remoteirc, remotechan, rc.users, rc.ts)
00:17 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 585, in relayJoins
00:17 <%PyLink>     remoteirc.proto.sjoin(rsid, remotechan, queued_users, ts=ts)
00:17 <%PyLink>   File "/home/gl/pylink/protocols/inspircd.py", line 118, in sjoin
00:17 <%PyLink>     namelist.append(','.join(userpair))
00:17 <%PyLink> TypeError: sequence item 1: expected str instance, NoneType found
00:17 <%PyLink> [ERROR] (apl) The offending hook data was: ['168', 'ENDBURST', {'ts': 1458631077}]
00:18 <%PyLink> [ERROR] (fun) Unhandled exception caught in hook <function handle_endburst at 0x7fc47997d378> from plugin "relay"
00:18 <%PyLink> Traceback (most recent call last):
00:18 <%PyLink>   File "/home/gl/pylink/classes.py", line 396, in callHooks
00:18 <%PyLink>     hook_func(self, numeric, command, parsed_args)
00:18 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 1174, in handle_endburst
00:18 <%PyLink>     initializeAll(irc)
00:18 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 44, in initializeAll
00:18 <%PyLink>     initializeChannel(irc, channel)
00:18 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 413, in initializeChannel
00:18 <%PyLink>     relayJoins(remoteirc, remotechan, rc.users, rc.ts)
00:18 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 586, in relayJoins
00:18 <%PyLink>     relayModes(irc, remoteirc, getRemoteSid(irc, remoteirc), channel, irc.channels[channel].modes)
00:18 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 728, in relayModes
00:18 <%PyLink>     remoteirc.proto.mode(rsid, remotechan, supported_modes)
00:18 <%PyLink>   File "/home/gl/pylink/protocols/inspircd.py", line 166, in mode
00:18 <%PyLink>     raise LookupError('No such PyLink client/server exists.')
00:18 <%PyLink> LookupError: No such PyLink client/server exists.
00:18 <%PyLink> [ERROR] (fun) The offending hook data was: ['877', 'ENDBURST', {'ts': 1458631080}]
00:18 <%PyLink> [WARNING] (ecode) No data received, disconnecting!
00:18 <%PyLink> [ERROR] (ecode) Unhandled exception caught in hook <function handle_endburst at 0x7fc47997d378> from plugin "relay"
00:18 <%PyLink> Traceback (most recent call last):
00:18 <%PyLink>   File "/home/gl/pylink/classes.py", line 396, in callHooks
00:18 <%PyLink>     hook_func(self, numeric, command, parsed_args)
00:18 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 1174, in handle_endburst
00:18 <%PyLink>     initializeAll(irc)
00:18 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 47, in initializeAll
00:18 <%PyLink>     initializeChannel(irc, channel)
00:18 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 413, in initializeChannel
00:18 <%PyLink>     relayJoins(remoteirc, remotechan, rc.users, rc.ts)
00:18 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 586, in relayJoins
00:18 <%PyLink>     relayModes(irc, remoteirc, getRemoteSid(irc, remoteirc), channel, irc.channels[channel].modes)
00:18 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 728, in relayModes
00:18 <%PyLink>     remoteirc.proto.mode(rsid, remotechan, supported_modes)
00:18 <%PyLink>   File "/home/gl/pylink/protocols/inspircd.py", line 166, in mode
00:18 <%PyLink> LookupError: No such PyLink client/server exists.
00:18 <%PyLink> [ERROR] (ecode) The offending hook data was: ['0UH', 'ENDBURST', {'ts': 1458631093}]
02:00 <%PyLink> [ERROR] (ovd) Unhandled exception caught in hook <function handle_messages at 0x7fc47997be18> from plugin "relay"
02:00 <%PyLink> Traceback (most recent call last):
02:00 <%PyLink>   File "/home/gl/pylink/classes.py", line 396, in callHooks
02:00 <%PyLink>     hook_func(self, numeric, command, parsed_args)
02:00 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 878, in handle_messages
02:00 <%PyLink>     remoteirc.proto.message(user, real_target, text)
02:00 <%PyLink>   File "/home/gl/pylink/protocols/ts6_common.py", line 100, in message
02:00 <%PyLink>     raise LookupError('No such PyLink client exists.')
02:00 <%PyLink> LookupError: No such PyLink client exists.
02:00 <%PyLink> [ERROR] (ovd) The offending hook data was: ['1MLAAAAQQ', 'PRIVMSG', {'ts': 1458637247, 'text': '\x02[\x0302freenode\x03]\x02 -\x0309doge\x03 is now known as -\x0312dogeball\x03', 'target': '#chat'}]
```

**Comment by GLolol** [comment]
2b16f25 may fix this (will reopen if issue arises again)

**Comment by GLolol** [comment]
Update: this issue seems possibly related to IRC states not clearing quick enough when a network disconnects. i.e., this error occurs because PyLink thinks the server relay tries to spawn already exists:
```
00:17 <%PyLink> Traceback (most recent call last):
00:17 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 228, in getRemoteSid
00:17 <%PyLink>     sid = relayservers[irc.name][remoteirc.name]
00:17 <%PyLink> KeyError: 'ovd'
00:17 <%PyLink> During handling of the above exception, another exception occurred:
00:17 <%PyLink> Traceback (most recent call last):
00:17 <%PyLink>   File "/home/gl/pylink/plugins/relay.py", line 236, in getRemoteSid
00:17 <%PyLink>     or remoteirc.name), endburst_delay=3)
00:17 <%PyLink>   File "/home/gl/pylink/protocols/inspircd.py", line 314, in spawnServer
00:17 <%PyLink>     raise ValueError('A server named %r already exists!' % name)
00:17 <%PyLink> ValueError: A server named 'ovd.relay' already exists!
```
