### ISSUE TITLE
protocols/unreal breaks with mixed 3.2/4.0 networks

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#193]
Reported by Rascle via IRC. Things like Unreal 3.2's older NICK syntax for introducing users cause PyLink to crash, because it isn't using an UID format as expected. It looks like we'd have to implement #145 in some way to solve this.
```
2016-04-01 21:13:48,899 [ERROR] (nn) The offending line was: <- NICK HelpServ 3 1456843578 services novernet.com services.novernet.com 0 +oS * :Help Server
2016-04-01 21:13:48,899 [DEBUG] (nn) <- NICK Global 3 1456843578 services novernet.com services.novernet.com 0 +ioS * :Global Noticer
2016-04-01 21:13:48,899 [ERROR] (nn) Caught error in handle_events, disconnecting!
Traceback (most recent call last):
  File "/home/mnorrbom/irc/relays/PyLink/classes.py", line 355, in runline
    hook_args = self.proto.handle_events(line)
  File "/home/mnorrbom/irc/relays/PyLink/protocols/ts6_common.py", line 205, in handle_events
    parsed_args = func(numeric, command, args)
  File "/home/mnorrbom/irc/relays/PyLink/protocols/ts6_common.py", line 250, in handle_nick
    oldnick = self.irc.users[numeric].nick
KeyError: '091'
```

**Comment by GLolol** [comment]
From discussion on `#unreal-devel`, this issue stems from Unreal 4.0 not translating any NICK messages for introducing users to UID (which we use). Servers are supposed to just deal with this by themselves, though there are implications of storing nicks in the users database raw too (nick collisions, etc.)
