### ISSUE TITLE
relay: Catastrophic failure when PyLink gets split off from a network (SID is missing)

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#354]
This problem occurs when `spawnRelayUser()` is called when the network in question was just split off (e.g. due to a server name conflict). Solution: add more error handling in the `spawnRelayUser / getRemoteUser` chain of events.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pylink/.local/lib/python3.4/site-packages/pylinkirc-1.0.2-py3.4.egg/pylinkirc/plugins/relay.py", line 261, in spawnRelayServer
    or remoteirc.name), endburst_delay=3)
  File "/home/pylink/.local/lib/python3.4/site-packages/pylinkirc-1.0.2-py3.4.egg/pylinkirc/protocols/inspircd.py", line 355, in spawnServer
    raise ValueError('Server %r is not a PyLink server!' % uplink)
ValueError: Server '0PY' is not a PyLink server!
2016-10-23 00:06:13,951 [ERROR] (fnode) Unhandled exception caught in hook <function handle_join at 0x7f71b10bc840> from plugin "pylinkirc.plugins.relay"
Traceback (most recent call last):
  File "/home/pylink/.local/lib/python3.4/site-packages/pylinkirc-1.0.2-py3.4.egg/pylinkirc/plugins/relay.py", line 396, in getRemoteUser
    u = relayusers[(irc.name, user)][remoteirc.name]
KeyError: 'fun'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pylink/.local/lib/python3.4/site-packages/pylinkirc-1.0.2-py3.4.egg/pylinkirc/classes.py", line 443, in callHooks
    hook_func(self, numeric, command, parsed_args)
  File "/home/pylink/.local/lib/python3.4/site-packages/pylinkirc-1.0.2-py3.4.egg/pylinkirc/plugins/relay.py", line 932, in handle_join
    relayJoins(irc, channel, users, ts, burst=False)
  File "/home/pylink/.local/lib/python3.4/site-packages/pylinkirc-1.0.2-py3.4.egg/pylinkirc/plugins/relay.py", line 661, in relayJoins
    u = getRemoteUser(irc, remoteirc, user)
  File "/home/pylink/.local/lib/python3.4/site-packages/pylinkirc-1.0.2-py3.4.egg/pylinkirc/plugins/relay.py", line 400, in getRemoteUser
    u = spawnRelayUser(irc, remoteirc, user, times_tagged=times_tagged)
  File "/home/pylink/.local/lib/python3.4/site-packages/pylinkirc-1.0.2-py3.4.egg/pylinkirc/plugins/relay.py", line 360, in spawnRelayUser
    opertype=opertype, server=rsid, ip=ip, realhost=realhost).uid
  File "/home/pylink/.local/lib/python3.4/site-packages/pylinkirc-1.0.2-py3.4.egg/pylinkirc/protocols/inspircd.py", line 48, in spawnClient
    raise ValueError('Server %r is not a PyLink server!' % server)
ValueError: Server '0PY' is not a PyLink server!
2016-10-23 00:06:13,952 [ERROR] (fnode) The offending hook data was: ['PSID@1', '315', {'channel': '#xtheme', 'parse_as': 'JOIN', 'users': {'PUID@25', 'PUID@21', 'PUID@28', 'PUID@27', 'PUID@26', 'PUID@24', 'PUID@23', 'PUID@1', 'PUID@22', 'PUID@20', 'PUID@29', 'PUID@19'}, 'modes': {('t', None), ('n', None)}, 'ts': 1477195568}]
2016-10-23 00:06:13,955 [INFO] (fun) Stopping connect loop (autoconnect value -1 is < 1).
```

**Comment by GLolol** [comment]
Should be fixed by 4246a3d113339c06bbb684517de5d19ecd20a8fc and 44743d860e52fe8d8e35b67a9d6f39f580a67ee0
