### ISSUE TITLE
Fix errors in mode/kick handlers when the sender isn't quite what we expect (servers can send modes too you know)

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#45]
im a bad programmer

```
2015-07-14 19:49:05,024 [DEBUG] (devel) Relay kick: remotechan for #chat on ovd is #chat
Traceback (most recent call last):
  File "/home/gl/pylink/plugins/relay.py", line 86, in getRemoteUser
    u = relayusers[(irc.name, user)][remoteirc.name]
KeyError: 'ovd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gl/pylink/protocols/inspircd.py", line 581, in handle_events
    hook_func(irc, numeric, command, parsed_args)
  File "/home/gl/pylink/plugins/relay.py", line 254, in handle_kick
    real_kicker = getRemoteUser(irc, remoteirc, kicker)
  File "/home/gl/pylink/plugins/relay.py", line 88, in getRemoteUser
    userobj = irc.users[user]
KeyError: '70M'
```
--------
```
Traceback (most recent call last):
  File "/home/gl/pylink/protocols/inspircd.py", line 581, in handle_events
    hook_func(irc, numeric, command, parsed_args)
  File "/home/gl/pylink/plugins/relay.py", line 341, in handle_mode
    relayModes(irc, remoteirc, numeric, target, modes)
  File "/home/gl/pylink/plugins/relay.py", line 316, in relayModes
    arg = getLocalUser(irc, arg)[1]
  File "/home/gl/pylink/plugins/relay.py", line 113, in getLocalUser
    if v[irc.name] == user:
KeyError: 'ovd'
```

**Comment by GLolol** [comment]
Adding enhancement tag because it's technically an enhancement to not have bugs like these in the code.
