### ISSUE TITLE
[relay] relayJoins is really buggy

### ISSUE THREAD

**Issue by GLolol** [GLolol/PyLink#74]
Somehow we're trying to spawn clients for users that don't exist?

```
Traceback (most recent call last):
  File "/home/gl/pylink/coreplugin.py", line 33, in handle_commands
    func(irc, source, cmd_args)
  File "/home/gl/pylink/plugins/relay.py", line 749, in link
    initializeChannel(irc, localchan)
  File "/home/gl/pylink/plugins/relay.py", line 229, in initializeChannel
    relayJoins(irc, channel, c.users, c.ts, c.modes)
  File "/home/gl/pylink/plugins/relay.py", line 595, in relayJoins
    assert user in irc.users, "(%s) How is this possible? %r isn't in our user database." % (irc.name, user)
AssertionError: (chary) How is this possible? '0ALAAAAAK' isn't in our user database.
```

Oddly, this only seems to occur when more than 2 networks are linked in one relay instance.

**Comment by GLolol** [comment]
`relayJoins` is breaking; it's trying to send relay pseudoclient UIDs to other networks, which means the `utils.isInternalClient()` check isn't working properly. Grrrr

**Comment by GLolol** [comment]
Still not working... **ffs**

**Comment by GLolol** [comment]
To give a bit more description: sometimes, the UID of another network's pseudoclient accidentally gets joined to a local channel's user list. When `relayJoins` tries to send local users later on, it's trying to fetch attributes of *a user that doesn't exist, but is in the channel's user list*. I don't really understand what's causing this, so any help would be highly appreciated.
